#!/bin/sh
# This starts an HTTP dev server with logging disabled.
echo 'Starting HTTP dev server (root = ./) on localhost:8000'
echo 'python3 -m http.server --bind 127.0.0.1  2>/dev/null >/dev/null'
python3 -m http.server --bind 127.0.0.1  2>/dev/null >/dev/null
